# Investigating the frequency of newly incorporated companies with the same post code in the UK

<br>

In [1]:
# importing numpy.
import numpy as np

# importing pandas.
import pandas as pd

# importing regular expressions.
import re

***

<br>

##### Reading in 500 companies incorporated in 2022 from Companies House

First 500 companies incorporated in the UK in 2022.  Search function available [here](https://find-and-update.company-information.service.gov.uk/advanced-search) [1].

In [2]:
data = "data\comp_house-2022.csv"

In [3]:
# Reading in CSV exported from Companies House.
comp_500 = pd.read_csv(data)

***

<br>

#### Creating Regex for post code

The regular expression for UK post codes was obtained [here](https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation) [2].

In [4]:
re_post = "([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|\
(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|\
([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})"

***

<br>

#### Searching post codes within the address

Running regular expression on addresses and adding post code to list

In [5]:
post = []

for i in comp_500["registered_office_address"]:
    match = re.search(re_post, i).group(0)
    post.append(match)

***

<br>

#### Adding post code as seperate column

In [6]:
comp_500["Post Code"] = post

***

<br>

#### Adding frequency of the post code as a column

In [7]:
# count of the 'Post Code' column and returning the count as a 'frequency' column.  Transform function applies the count to each row. [3]
comp_500['PO frequency'] = comp_500.groupby("Post Code")["Post Code"].transform('count')

***

<br>

#### Displaying dataframe

Displaying top 50 rows in decending order by 'frequency'.

In [8]:
comp_500.sort_values('PO frequency', ascending=False).head(50)

,company_name,company_number,company_status,company_type,dissolution_date,incorporation_date,nature_of_business,registered_office_address,Post Code,PO frequency
307,121 PROPERTY SOLUTIONS LIMITED,13825040,Active,Private limited company,NaN,03/01/2022,68320,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
129,ADELE & GIUSEPPE LTD,13824537,Active,Private limited company,NaN,01/01/2022,56103,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
218,STAY SAFE GROUP LTD,13825222,Active,Private limited company,NaN,03/01/2022,70229 80100,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
305,ACE INFINITY LTD,13825010,Active,Private limited company,NaN,03/01/2022,93290,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
306,BRIGHTER CLUB LTD,13825044,Active,Private limited company,NaN,03/01/2022,86900,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
301,LNTJ HOLDINGS LTD,13824990,Active,Private limited company,NaN,03/01/2022,64209,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
309,23HEATING LTD,13825025,Active,Private limited company,NaN,03/01/2022,43220,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
311,J10XJJ LIMITED,13825011,Active,Private limited company,NaN,03/01/2022,59112,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
492,TECHTASTIK LTD,13831787,Active,Private limited company,NaN,06/01/2022,47429,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
299,ACCEPTICON LTD,13825000,Active,Private limited company,NaN,03/01/2022,47910 82990,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
338,THE ESSENTIALS OUTLET LTD,13825121,Active,Private limited company,NaN,03/01/2022,47190,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
315,FITCHLEA SERVICES LTD,13824996,Active,Private limited company,NaN,03/01/2022,43999,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
203,LUXURIES SECURITY LTD,13825120,Active,Private limited company,NaN,03/01/2022,80100,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
316,META INSIGHT CONSULTANCY LTD,13825006,Active,Private limited company,NaN,03/01/2022,82990 96090,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
319,TOP QUALITY FRUIT LTD,13825055,Active,Private limited company,NaN,03/01/2022,47210,86-90 Paul Street London EC2A 4NE,EC2A 4NE,15
106,TILLY SIMSON LIMITED,13824368,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
109,BRADLEY WOODS LIMITED,13824380,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
49,DION ROTHMERE LIMITED,13824433,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
107,NINA WILD LIMITED,13824370,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
50,TARA BROOKE LIMITED,13824423,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
104,ROSIE FARRAR LIMITED,13824366,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
394,CONCEPT FM LIMITED,13831531,Active,Private limited company,NaN,06/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
100,IZZY BUCK LIMITED,13824357,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
99,KITTY KRAMER LIMITED,13824356,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
190,DONT RUN LIMITED,13824973,Active,Private limited company,NaN,03/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
111,OLIVER DRAX LIMITED,13824385,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
420,PRESTIGE FREIGHT LIMITED,13832071,Active,Private limited company,NaN,06/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
8,POLLY RHODES LIMITED,13824438,Active,Private limited company,NaN,01/01/2022,99999,Metro House 57 Pepper Road Leeds LS10 2RU,LS10 2RU,13
385,PLANETEGAME LTD,13831384,Active,Private limited company,NaN,06/01/2022,47910,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,4
426,CSMB LTD,13832140,Active,Private limited company,NaN,06/01/2022,46160 47650,20-22 Wenlock Road London N1 7GU,N1 7GU,4
398,THE PRESTIGE CARE GROUP LTD,13831521,Active,Private limited company,NaN,06/01/2022,86102 86900 87100 87300,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,4
436,JULESANT LTD,13832569,Active,Private limited company,NaN,06/01/2022,70229 71122 71129 74902,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,4
466,CHROME PROPERTY MANAGEMENT LTD,13833060,Active,Private limited company,NaN,06/01/2022,68100 68209,20-22 Wenlock Road London N1 7GU,N1 7GU,4
400,GRANITE CONSULTANCY LIMITED,13831523,Active,Private limited company,NaN,06/01/2022,64999 96090,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,4
491,SILICON HOMES LTD,13831774,Active,Private limited company,NaN,06/01/2022,68209,20-22 Wenlock Road London N1 7GU,N1 7GU,4
158,SK DEVELOPMENT SERVICES LIMITED,13824763,Active,Private limited company,NaN,02/01/2022,41100,20-22 Wenlock Road London N1 7GU,N1 7GU,4
19,CRAVEN CAPITAL GROUP LIMITED,13824528,Active,Private limited company,NaN,01/01/2022,70229,Garden Cottage Rooksmead Road Sunbury-On-Thame...,TW16 6PD,2
191,"METASEQUOIA OVERSEAS CONSULTING CO., LTD",13824974,Active,Private limited company,NaN,03/01/2022,85600,"C/O Xiang And Co, Burrell House, 44 Broadway L...",E15 1XH,2
413,NEXT TUYERE LIMITED,13831868,Active,Private limited company,NaN,06/01/2022,99999,291 Brighton Road South Croydon CR2 6EQ,CR2 6EQ,2
439,BESTONE GROUP LTD,13832622,Active,Private limited company,NaN,06/01/2022,22230 24540 46150 93130,291 Brighton Road South Croydon CR2 6EQ,CR2 6EQ,2
65,CRAVEN CAPITAL CONSULTING LIMITED,13824521,Active,Private limited company,NaN,01/01/2022,70229,Garden Cottage Rooksmead Road Sunbury-On-Thame...,TW16 6PD,2
450,HARMONY PRINT SOLUTIONS LTD,13832761,Active,Private limited company,NaN,06/01/2022,18129,"Suite A, 82 James Carter Road Mildenhall Bury ...",IP28 7DE,2
52,CASTLE CLEANING LTD,13824447,Active,Private limited company,NaN,01/01/2022,81210,Unit A 82 James Carter Road Mildenhall Industr...,IP28 7DE,2
213,IINEX MEDIA LTD,13825173,Active,Private limited company,NaN,03/01/2022,73120,2-4 Millgate Stockport SK1 2LX,SK1 2LX,2
114,IINEX PROPERTIES LTD,13824397,Active,Private limited company,NaN,01/01/2022,98000,2-4 Millgate Stockport SK1 2LX,SK1 2LX,2
468,TBL CONTRACTORS LTD,13833099,Active,Private limited company,NaN,06/01/2022,43390 43999,44 Broadway London E15 1XH,E15 1XH,2
329,FLATTOUT TOWBARS & TRANSPORT LTD,13825085,Active,Private limited company,NaN,03/01/2022,45200,79 Brook Street Lye Stourbridge DY9 8SN,DY9 8SN,1
335,FULL CAPTURE LTD,13825112,Active,Private limited company,NaN,03/01/2022,59112 74202,33 Farmer Ward Road Kenilworth CV8 2DJ,CV8 2DJ,1
365,PERFECT60 LTD,13825298,Active,Private limited company,NaN,03/01/2022,56103,60 Manham Hill Eastfield Scarborough YO11 3DG,YO11 3DG,1
366,OMEGA GLASS RECYCLING LIMITED,13825316,Active,Private limited company,NaN,03/01/2022,38210,65 Pienna Apartments 2 Elvin Gardens Wembley H...,HA9 0GN,1

***

<br>

## References

1. https://find-and-update.company-information.service.gov.uk/advanced-search
2. https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation
3. https://stackoverflow.com/questions/22391433/count-the-frequency-that-a-value-occurs-in-a-dataframe-column

***

# End