# Investigating the frequency of newly incorporated companies with the same post code in the UK

<br>

In [1]:
# importing numpy.
import numpy as np

# importing pandas.
import pandas as pd

# importing regular expressions.
import re

***

<br>

##### Reading in 500 companies incorporated in 2022 from Companies House

First 500 companies incorporated in the UK in 2022.  Search function available [here](https://find-and-update.company-information.service.gov.uk/advanced-search) [1].

In [2]:
data = "data\comp_house-13012022.csv"

In [3]:
# Reading in CSV exported from Companies House.
comp_500 = pd.read_csv(data)

***

<br>

#### Creating Regex for post code

The regular expression for UK post codes was obtained [here](https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation) [2].

In [4]:
re_post = "([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|\
(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|\
([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})"

***

<br>

#### Searching post codes within the address

Running regular expression on addresses and adding post code to list

In [5]:
post = []

for i in comp_500["registered_office_address"]:
    match = re.search(re_post, i).group(0)
    post.append(match)

***

<br>

#### Adding post code as seperate column

In [6]:
comp_500["Post Code"] = post

***

<br>

#### Adding frequency of the post code as a column

In [7]:
# count of the 'Post Code' column and returning the count as a 'frequency' column.  Transform function applies the count to each row. [3]
comp_500['PO frequency'] = comp_500.groupby("Post Code")["Post Code"].transform('count')

***

<br>

#### Displaying dataframe

Displaying top 50 rows in decending order by 'frequency'.

In [8]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

comp_500.sort_values('PO frequency', ascending=False).head(100)

,company_name,company_number,company_status,company_type,dissolution_date,incorporation_date,nature_of_business,registered_office_address,Post Code,PO frequency
205,CHANGING LIVES SUPPORT LTD,13845879,Active,Private limited by guarantee without share cap...,NaN,13/01/2022,86900 88990,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
193,MOUAD LTD,13845828,Active,Private limited company,NaN,13/01/2022,47710,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
197,AION COMMUNICATIONS LTD,13846365,Active,Private limited company,NaN,13/01/2022,61900,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
204,COMPLEX ADAPTIVE SOFTWARE SYSTEMS LTD,13845881,Active,Private limited company,NaN,13/01/2022,58290 62011 62012 72190,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
198,ANIJIE GLOBAL LTD,13846367,Active,Private limited company,NaN,13/01/2022,96090,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
199,SEMPER EXCELSIUS LTD,13846366,Active,Private limited company,NaN,13/01/2022,68100 68209,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
200,ANALYTICR LTD,13846386,Active,Private limited company,NaN,13/01/2022,96090,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
211,NEXT STEP TECH SERVICES LTD,13845676,Active,Private limited company,NaN,13/01/2022,62020 62090,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
210,ADMEP LTD,13845675,Active,Private limited company,NaN,13/01/2022,62012 62020 62090,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
209,LOSOMO STUDIO LIMITED,13845672,Active,Private limited company,NaN,13/01/2022,96090,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
201,MINIMALIST GOLF LTD,13846545,Active,Private limited company,NaN,13/01/2022,96090,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
202,VIRTUAL GREEN ENERGY LIMITED,13845711,Active,Private limited company,NaN,13/01/2022,35110 47910,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
196,ARUTBA LTD,13845989,Active,Private limited company,NaN,13/01/2022,64205 64301 64999 66110,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
195,GLODIVE LTD,13845957,Active,Private limited company,NaN,13/01/2022,62020 62090 74300 85590,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
194,CYBERNITE TECHNOLOGIES LTD,13845831,Active,Private limited company,NaN,13/01/2022,62012 62020 62090 63110,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
192,HSAR LIMITED,13845639,Active,Private limited company,NaN,13/01/2022,47910,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
186,TRANS 2000 LIMITED,13847319,Active,Private limited company,NaN,13/01/2022,49410,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
206,ONE LOOKOUT LTD,13846068,Active,Private limited company,NaN,13/01/2022,58110 58210 58290 62012,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
207,INFINITE SOLUTIONS PARTNERS LTD,13846613,Active,Private limited company,NaN,13/01/2022,64209,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
208,MERITA LTD,13845680,Active,Private limited company,NaN,13/01/2022,47190 47770 47990 62020,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
203,BERNASHI LTD,13845868,Active,Private limited company,NaN,13/01/2022,45400 46760 47990,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
185,INFINITY WAREHOUSING & LOGISTICS LTD,13847257,Active,Private limited company,NaN,13/01/2022,52103 52243,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
184,LOSREX LTD,13846431,Active,Private limited company,NaN,13/01/2022,46180 46760,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
187,CAGMILITARIA LTD,13846565,Active,Private limited company,NaN,13/01/2022,47791 47799,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
188,NARROWBRIDGE LIMITED,13846567,Active,Private limited company,NaN,13/01/2022,64303 69109 70229 74909,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
189,TICS TECHNOLOGY LIMITED,13846816,Active,Private limited company,NaN,13/01/2022,27510 27520 46439 46900,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
190,ATAKTON LTD,13847610,Active,Private limited company,NaN,13/01/2022,62020 70229 74100 90030,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
191,BGD TECHNOLOGIES (UK) LIMITED,13846263,Active,Private limited company,NaN,13/01/2022,47190 47910 47990,71-75 Shelton Street Covent Garden London WC2H...,WC2H 9JQ,28
402,MYL HOLDING LTD,13846196,Active,Private limited company,NaN,13/01/2022,64209,20-22 Wenlock Road London N1 7GU,N1 7GU,15
406,PJARCHITECTURE LTD,13846396,Active,Private limited company,NaN,13/01/2022,71111,20-22 Wenlock Road London N1 7GU,N1 7GU,15
405,FYLA SERVICES LTD,13846081,Active,Private limited company,NaN,13/01/2022,41201 41202 43390,20-22 Wenlock Road London N1 7GU,N1 7GU,15
404,LIFE FUNNY COOL ELECTRONIC COMMERCE LTD,13845860,Active,Private limited company,NaN,13/01/2022,1110,20-22 Wenlock Road London N1 7GU,N1 7GU,15
403,STOCKLOT SOLUTIONS LTD,13847504,Active,Private limited company,NaN,13/01/2022,46160 46410 46420 47510,20-22 Wenlock Road London N1 7GU,N1 7GU,15
407,BOSS MAN BARBERS LTD,13845704,Active,Private limited company,NaN,13/01/2022,96020,20-22 Wenlock Road London N1 7GU,N1 7GU,15
401,M CORPORATION LTD,13846193,Active,Private limited company,NaN,13/01/2022,70229,20-22 Wenlock Road London N1 7GU,N1 7GU,15
396,INTERNATIONAL CONGRESS FOR HEALTH SPECIALTIES LTD,13846285,Active,Private limited company,NaN,13/01/2022,99999,20-22 Wenlock Road London N1 7GU,N1 7GU,15
393,TRIANGLE PARTNERS LIMITED,13846110,Active,Private limited company,NaN,13/01/2022,64209,20-22 Wenlock Road London N1 7GU,N1 7GU,15
394,BLUE TIGER INTERNATIONAL LTD,13846731,Active,Private limited company,NaN,13/01/2022,47910,20-22 Wenlock Road London N1 7GU,N1 7GU,15
400,HASSAN HUSSEIN LTD,13847579,Active,Private limited company,NaN,13/01/2022,47910 68320 98000,20-22 Wenlock Road London N1 7GU,N1 7GU,15
395,ASIA EXPERIENCED LTD,13847433,Active,Private limited company,NaN,13/01/2022,73110,20-22 Wenlock Road London N1 7GU,N1 7GU,15
398,BURGER BOXXX LTD,13846873,Active,Private limited company,NaN,13/01/2022,56103,20-22 Wenlock Road London N1 7GU,N1 7GU,15
399,PREMIUM SPIRITS GROUP LTD,13847582,Active,Private limited company,NaN,13/01/2022,11010 46342,20-22 Wenlock Road London N1 7GU,N1 7GU,15
397,ANGELIS LTD,13846277,Active,Private limited company,NaN,13/01/2022,96020,20-22 Wenlock Road London N1 7GU,N1 7GU,15
93,DMI - DIGITAL MARKETING AGENCY LTD,13846045,Active,Private limited company,NaN,13/01/2022,73110,Kemp House 160 City Road London EC1V 2NX,EC1V 2NX,10
92,ARIAVA LTD,13845834,Active,Private limited company,NaN,13/01/2022,46190 46900 47190 47910,Kemp House 160 City Road London EC1V 2NX,EC1V 2NX,10
96,SINEKIT LTD,13845937,Active,Private limited company,NaN,13/01/2022,47910,Kemp House 152 - 160 City Road London EC1V 2NX,EC1V 2NX,10
95,IRTZA & IMITED LTD,13846051,Active,Private limited company,NaN,13/01/2022,47990,Kemp House 152-160 City Road London EC1V 2NX,EC1V 2NX,10
94,JERCEY LTD,13845707,Active,Private limited company,NaN,13/01/2022,64305,Kemp House 160 City Road London EC1V 2NX,EC1V 2NX,10
91,AFORME LTD,13845685,Active,Private limited company,NaN,13/01/2022,47910,Kemp House 160 City Road London EC1V 2NX,EC1V 2NX,10
90,TRIVOLI LIMITED,13846292,Active,Private limited company,NaN,13/01/2022,43210 45112 46341 47190,Kemp House 160 City Road London EC1V 2NX,EC1V 2NX,10
89,CLEAN ACCESS LTD,13846798,Active,Private limited company,NaN,13/01/2022,81210,Kemp House 160 City Road London EC1V 2NX,EC1V 2NX,10
88,PRIMA ARINDA LTD,13847321,Active,Private limited company,NaN,13/01/2022,96090,Kemp House 160 City Road London EC1V 2NX,EC1V 2NX,10
87,STK INTERNATIONAL LTD,13847282,Active,Private limited company,NaN,13/01/2022,62020 62090 63110 82990,Kemp House 160 City Road London EC1V 2NX,EC1V 2NX,10
166,MOBIUS INC. LIMITED,13845709,Active,Private limited company,NaN,13/01/2022,74901,86-90 Paul Street 3rd Floor London EC2A 4NE,EC2A 4NE,7
165,CUTS HEAL LIMITED,13846187,Active,Private limited company,NaN,13/01/2022,47910,86-90 Paul Street London EC2A 4NE,EC2A 4NE,7
305,GYLT FREE LTD,13847435,Active,Private limited company,NaN,13/01/2022,82990,3rd Floor 86-90 Paul Street London EC2A 4NE,EC2A 4NE,7
164,M@M HANDYMAN AND BRICKWORK SERVICES LIMITED,13846205,Active,Private limited company,NaN,13/01/2022,23320,86-90 Paul Street London EC2A 4NE,EC2A 4NE,7
163,SRS SALES LTD,13846198,Active,Private limited company,NaN,13/01/2022,47910,86-90 Paul Street London EC2A 4NE,EC2A 4NE,7
162,RSHELLE LTD,13847063,Active,Private limited company,NaN,13/01/2022,47770,86-90 Paul Street London EC2A 4NE,EC2A 4NE,7
161,JACKCO GROUP INTERNATIONAL LIMITED,13847081,Active,Private limited company,NaN,13/01/2022,47910 62090,86-90 Paul Street London EC2A 4NE,EC2A 4NE,7
459,KALOISE SERVICES LTD,13846320,Active,Private limited company,NaN,13/01/2022,82990,123 St. Marks Road Enfield EN1 1BJ,EN1 1BJ,4
460,PARAFTA SERVICES LTD,13845961,Active,Private limited company,NaN,13/01/2022,82990,123 St. Marks Road Enfield EN1 1BJ,EN1 1BJ,4
461,LALMETO SERVICES LTD,13845942,Active,Private limited company,NaN,13/01/2022,82990,123 St. Marks Road Enfield EN1 1BJ,EN1 1BJ,4
462,GEPESE SERVICES LTD,13846064,Active,Private limited company,NaN,13/01/2022,82990,123 St. Marks Road Enfield EN1 1BJ,EN1 1BJ,4
20,INDUS PROCESS LTD,13845852,Active,Private limited company,NaN,13/01/2022,47990,Unit 13 Freeland Park Wareham Road Lytchett Ma...,BH16 6FA,3
85,AI STACK LIMITED,13847540,Active,Private limited company,NaN,13/01/2022,47990,Lytchett House 13 Freeland Park Wareham Road P...,BH16 6FA,3
19,TUFF FIT LTD,13846924,Active,Private limited company,NaN,13/01/2022,32300,"Unit 13 Freeland Park, Wareham Road, Lytechett...",BH16 6FA,3
321,PERATOK SOLUTIONS LTD,13847038,Active,Private limited company,NaN,13/01/2022,82990,34 Lodge Road Aston Birmingham B6 6LU,B6 6LU,3
320,APENADO SOLUTIONS LTD,13845974,Active,Private limited company,NaN,13/01/2022,82990,34 Lodge Road Aston Birmingham B6 6LU,B6 6LU,3
50,SHORTIEBULLZ 24HR PET RESPONSE LIMITED,13846811,Active,Private limited company,NaN,13/01/2022,99999,Studio 210 134-146 Curtain Road London EC2A 3AR,EC2A 3AR,3
51,3RD EYE SECURITY LIMITED,13845692,Active,Private limited company,NaN,13/01/2022,80100,Studio 210 134-146 Curtain Road London EC2A 3AR,EC2A 3AR,3
52,BEYOND PLUMBING AND HEATING SOLUTIONS LIMITED,13845802,Active,Private limited company,NaN,13/01/2022,35230,Studio 210 134-146 Curtain Road London EC2A 3AR,EC2A 3AR,3
319,LEDIAKA SOLUTIONS LTD,13846261,Active,Private limited company,NaN,13/01/2022,82990,34 Lodge Road Aston Birmingham B6 6LU,B6 6LU,3
127,TYNE TEES EPC LTD,13846262,Active,Private limited company,NaN,13/01/2022,74901,Collingwood Buildings 38 Collingwood Street Ne...,NE1 1JF,2
126,D & L PROPERTY GROUP LTD,13846394,Active,Private limited company,NaN,13/01/2022,68209,Collingwood Buildings 38 Collingwood Street Ne...,NE1 1JF,2
219,OCTOPUS ENERGY DEVELOPMENT PARTNERSHIP LP LIMITED,13847551,Active,Private limited company,NaN,13/01/2022,64209,6th Floor 33 Holborn London EC1N 2HT,EC1N 2HT,2
218,OCTOPUS ENERGY DEVELOPMENT PARTNERSHIP GP LIMITED,13847317,Active,Private limited company,NaN,13/01/2022,64209,6th Floor 33 Holborn London EC1N 2HT,EC1N 2HT,2
498,LOTTIE KNIGHT LIMITED,13846158,Active,Private limited company,NaN,13/01/2022,47910,1 Crescent Cottages Pound Crescent Fetcham Lea...,KT22 9JA,2
235,RLG WAREHOUSELINK LIMITED,13846415,Active,Private limited company,NaN,13/01/2022,52103,6 Perth House Priors Haw Road Corby NN17 5JG,NN17 5JG,2
32,C1760 LTD,13846175,Active,Private limited company,NaN,13/01/2022,90040,Third Floor 104-108 Oxford Street London W1D 1LP,W1D 1LP,2
6,MANOR PARK ALLURE LTD,SC719707,Active,Private limited company,NaN,13/01/2022,68100,Westburn House Mcnee Road Prestwick KA9 2PB,KA9 2PB,2
7,AULGIRTH (B) ALLURE LTD,SC719748,Active,Private limited company,NaN,13/01/2022,68100,Westburn House Mcnee Road Prestwick KA9 2PB,KA9 2PB,2
234,GRH CLEARWAREHOUSE LIMITED,13846379,Active,Private limited company,NaN,13/01/2022,52103,6 Perth House Priors Haw Road Corby NN17 5JG,NN17 5JG,2
326,GODFREY GARAGE (HOLBEACH) LTD,13846331,Active,Private limited company,NaN,13/01/2022,45200,32 The Crescent Spalding PE11 1AF,PE11 1AF,2
327,NEW VIEW PROPERTY CARE LTD,13846747,Active,Private limited company,NaN,13/01/2022,41202,32 The Crescent Spalding PE11 1AF,PE11 1AF,2
273,GERBERA PRINT LTD,13847460,Active,Private limited company,NaN,13/01/2022,47910,483 Green Lanes London N13 4BS,N13 4BS,2
272,INSTA EUROPE LTD,13846242,Active,Private limited company,NaN,13/01/2022,73110,483 Green Lanes London N13 4BS,N13 4BS,2
441,SARS SPA LTD,13847035,Active,Private limited company,NaN,13/01/2022,93130,16 Dolphin Street Manchester M12 6BG,M12 6BG,2
440,AKAS COMPANIES LTD,13846818,Active,Private limited company,NaN,13/01/2022,64204,16 Dolphin Street Manchester M12 6BG,M12 6BG,2
77,IDEAS2SHOP LTD,13845701,Active,Private limited company,NaN,13/01/2022,47910,Office 2281 182-184 High Street North East Ham...,E6 2JA,2
76,SKILHIL RECRUITMENT LTD LIMITED,13845768,Active,Private limited company,NaN,13/01/2022,78109,Office 2289 182-184 High Street North East Ham...,E6 2JA,2
31,HONEYBEE BIOTECHNOLOGIES LTD,13845854,Active,Private limited company,NaN,13/01/2022,72110,Third Floor 104-108 Oxford Street London W1D 1LP,W1D 1LP,2
497,MISTY VALE LIMITED,13846288,Active,Private limited company,NaN,13/01/2022,47910,1 Crescent Cottages Pound Crescent Fetcham Lea...,KT22 9JA,2
293,JP INSTALLATIONS LTD,13847373,Active,Private limited company,NaN,13/01/2022,43320,41 Chestnut Avenue West Cross Swansea SA3 5NL,SA3 5NL,1
288,PHANTOM CLOUDS LTD,NI684982,Active,Private limited company,NaN,13/01/2022,90030,43 Croft Hill Belfast BT8 6GX,BT8 6GX,1
287,CAPITAL CARS ELMBRIDGE LTD,13845774,Active,Private limited company,NaN,13/01/2022,49320,43 Danesfield Close Walton-On-Thames KT12 3BP,KT12 3BP,1
297,E&A CAPITAL LIMITED,13847163,Active,Private limited company,NaN,13/01/2022,68100,4 Rectory Lane Birmingham B36 9DH,B36 9DH,1
296,VINCENT & MORGAN LTD,13846920,Active,Private limited company,NaN,13/01/2022,68209,4 St. Marys Mews 3 West Street Exeter EX1 1BB,EX1 1BB,1
289,QUEENSGATE BALLYMONEY LIMITED,NI684961,Active,Private limited company,NaN,13/01/2022,98000,42a-44a New Row Coleraine BT52 1AF,BT52 1AF,1
292,CLICKTAX LONDON LTD,13845693,Active,Private limited company,NaN,13/01/2022,69201,41 High Street Royston SG8 9AW,SG8 9AW,1

***

<br>

## References

1. https://find-and-update.company-information.service.gov.uk/advanced-search
2. https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation
3. https://stackoverflow.com/questions/22391433/count-the-frequency-that-a-value-occurs-in-a-dataframe-column

***

# End